package net.unit8.tieto.generator.output;

import net.unit8.tieto.generator.ai.GeneratedFunction;
import net.unit8.tieto.generator.parser.FunctionNaming;
import net.unit8.tieto.generator.parser.GeneratorException;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.List;

/**
 * Writes generated SQL functions to one {@code <repository>.sql} file.
 */
public final class SqlFileWriter {

    /**
     * Writes the generated functions to {@code <repository>.sql} in the output directory.
     *
     * <p>When {@code replaceExisting} is true the file is rewritten from scratch (a full
     * regeneration). Otherwise the new functions are <em>appended</em> to an existing file
     * so that functions skipped this run (already present in the file) are preserved rather
     * than dropped; a missing file is created fresh either way.</p>
     *
     * @param outputDir the output directory
     * @param repositoryName the repository name (used for file naming)
     * @param functions the generated functions to write
     * @param replaceExisting rewrite the whole file (true) or append the new functions (false)
     * @param provenance backend/model description recorded in the header for auditability
     */
    public void write(Path outputDir, String repositoryName,
                      List<GeneratedFunction> functions, boolean replaceExisting,
                      String provenance) {
        try {
            Files.createDirectories(outputDir);
            Path outputFile = outputDir.resolve(FunctionNaming.camelToSnake(repositoryName) + ".sql");
            String functionBlocks = renderFunctions(functions);

            if (replaceExisting || !Files.exists(outputFile)) {
                String header = "-- Generated by tieto-generator\n"
                        + "-- Source: " + repositoryName + "\n"
                        + "-- Generator: " + provenance + "\n\n";
                Files.writeString(outputFile, header + functionBlocks);
            } else {
                Files.writeString(outputFile, functionBlocks, StandardOpenOption.APPEND);
            }
        } catch (IOException e) {
            throw new GeneratorException("Failed to write SQL file", e);
        }
    }

    private static String renderFunctions(List<GeneratedFunction> functions) {
        var sb = new StringBuilder();
        for (GeneratedFunction func : functions) {
            sb.append(func.sqlBody());
            if (!func.sqlBody().endsWith(";")) {
                sb.append(';');
            }
            sb.append("\n\n");
        }
        return sb.toString();
    }
}
