package net.unit8.tieto.generator.output;

import net.unit8.tieto.generator.ai.GeneratedFunction;
import net.unit8.tieto.generator.parser.FunctionNaming;
import net.unit8.tieto.generator.parser.GeneratorException;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.List;

/**
 * Writes generated SQL functions to one {@code <repository>.sql} file, one tieto-delimited block
 * per function (see {@link SqlFunctionFile}).
 */
public final class SqlFileWriter {

    /**
     * Writes the generated functions to {@code <repository>.sql} in the output directory.
     *
     * <p>A fresh file (or {@code replaceExisting}) is written from scratch. Otherwise the new
     * functions are <em>merged</em> into the existing file: each regenerated function replaces only
     * its own {@code tieto:begin/end} block, functions not regenerated this run are preserved, and
     * blocks are re-emitted in a stable name-sorted order — so a partial regeneration yields a diff
     * limited to the changed function(s). A file with no tieto markers (written before the
     * delimiters existed, or hand-authored) cannot be merged safely, so its functions are appended
     * with a warning; re-run with {@code --force} to rewrite it in the delimited format.</p>
     *
     * @param outputDir the output directory
     * @param repositoryName the repository name (used for file naming)
     * @param functions the generated functions to write
     * @param replaceExisting rewrite the whole file (true) or merge the new functions (false)
     * @param provenance backend/model description recorded in the header for auditability
     */
    public void write(Path outputDir, String repositoryName,
                      List<GeneratedFunction> functions, boolean replaceExisting,
                      String provenance) {
        try {
            Files.createDirectories(outputDir);
            Path outputFile = outputDir.resolve(FunctionNaming.camelToSnake(repositoryName) + ".sql");

            if (replaceExisting || !Files.exists(outputFile)) {
                SqlFunctionFile file = SqlFunctionFile.fresh(header(repositoryName, provenance));
                file.putAll(functions);
                Files.writeString(outputFile, file.render());
                return;
            }

            SqlFunctionFile file = SqlFunctionFile.parse(Files.readString(outputFile));
            if (file.isLegacy()) {
                System.err.println("Warning: " + outputFile + " has no tieto:begin/end markers;"
                        + " appending the new functions instead of merging. Re-run with --force to"
                        + " rewrite it in the delimited format for clean diffs on future regenerations.");
                Files.writeString(outputFile, renderLegacyBlocks(functions), StandardOpenOption.APPEND);
                return;
            }
            file.putAll(functions);
            Files.writeString(outputFile, file.render());
        } catch (IOException e) {
            throw new GeneratorException("Failed to write SQL file", e);
        }
    }

    private static String header(String repositoryName, String provenance) {
        return "-- Generated by tieto-generator\n"
                + "-- Source: " + commentValue(repositoryName) + "\n"
                + "-- Generator: " + commentValue(provenance);
    }

    /**
     * Flattens a value interpolated into a single-line {@code -- } comment: CR/LF
     * are replaced with spaces so the value cannot break out of the comment and
     * inject a bare SQL line into the generated file.
     */
    private static String commentValue(String value) {
        return value == null ? "" : value.replaceAll("[\\r\\n]+", " ");
    }

    /** Plain, marker-less rendering used only to append to a legacy (marker-less) file. */
    private static String renderLegacyBlocks(List<GeneratedFunction> functions) {
        var sb = new StringBuilder();
        for (GeneratedFunction func : functions) {
            sb.append(func.sqlBody());
            if (!func.sqlBody().endsWith(";")) {
                sb.append(';');
            }
            sb.append("\n\n");
        }
        return sb.toString();
    }
}
