package net.unit8.tieto.generator.output;

import net.unit8.tieto.generator.ai.GeneratedFunction;
import net.unit8.tieto.generator.parser.GeneratorException;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Writes generated SQL functions to .sql files.
 */
public class SqlFileWriter {

    /**
     * Writes all generated functions to a single SQL file in the output directory.
     *
     * @param outputDir the output directory
     * @param repositoryName the repository name (used for file naming)
     * @param functions the generated functions
     */
    public void write(Path outputDir, String repositoryName, List<GeneratedFunction> functions) {
        try {
            Files.createDirectories(outputDir);

            String fileName = camelToSnake(repositoryName) + ".sql";
            Path outputFile = outputDir.resolve(fileName);

            var sb = new StringBuilder();
            sb.append("-- Generated by tieto-generator\n");
            sb.append("-- Source: ").append(repositoryName).append("\n\n");

            for (GeneratedFunction func : functions) {
                sb.append(func.sqlBody());
                if (!func.sqlBody().endsWith(";")) {
                    sb.append(';');
                }
                sb.append("\n\n");
            }

            Files.writeString(outputFile, sb.toString());
        } catch (IOException e) {
            throw new GeneratorException("Failed to write SQL file", e);
        }
    }

    private static String camelToSnake(String camel) {
        return camel
                .replaceAll("([A-Z]+)([A-Z][a-z])", "$1_$2")
                .replaceAll("([a-z0-9])([A-Z])", "$1_$2")
                .toLowerCase();
    }
}
