-- PostgreSQL Functions: the OrderRepository implementation.
--
-- In production these are generated by tieto-generator (AI) from the Repository
-- interface Javadoc + the schema, then reviewed and committed. Here they are hand-written
-- to keep the example self-contained (docker compose loads this file at init). Either way,
-- the Repository tests in src/test are the gate: the generated/committed SQL is accepted
-- only if those tests pass. See OrderRepositoryTest.

-- OrderRepository.findById(Long id) -> Optional<Order>
CREATE OR REPLACE FUNCTION order_repository_find_by_id_v1(p_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    result JSONB;
BEGIN
    SELECT jsonb_build_object(
        'id', o.id,
        'customerId', o.customer_id,
        'status', o.status,
        'createdAt', o.created_at,
        'lines', COALESCE((
            SELECT jsonb_agg(jsonb_build_object(
                'productId', ol.product_id,
                'quantity', ol.quantity,
                'unitPrice', ol.unit_price
            ) ORDER BY ol.id)
            FROM order_lines ol WHERE ol.order_id = o.id
        ), '[]'::jsonb)
    ) INTO result
    FROM orders o
    WHERE o.id = p_id;

    RETURN result;
END;
$$;

-- OrderRepository.findByCustomerId(String customerId) -> List<Order>
CREATE OR REPLACE FUNCTION order_repository_find_by_customer_id_v1(p_customer_id TEXT)
RETURNS SETOF JSONB
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT jsonb_build_object(
        'id', o.id,
        'customerId', o.customer_id,
        'status', o.status,
        'createdAt', o.created_at,
        'lines', COALESCE((
            SELECT jsonb_agg(jsonb_build_object(
                'productId', ol.product_id,
                'quantity', ol.quantity,
                'unitPrice', ol.unit_price
            ) ORDER BY ol.id)
            FROM order_lines ol WHERE ol.order_id = o.id
        ), '[]'::jsonb)
    )
    FROM orders o
    WHERE o.customer_id = p_customer_id
    ORDER BY o.created_at DESC, o.id DESC;
END;
$$;

-- OrderRepository.save(Order order) -> void
CREATE OR REPLACE FUNCTION order_repository_save_v1(p_order JSONB)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    new_order_id BIGINT;
    line JSONB;
BEGIN
    INSERT INTO orders (customer_id, status, created_at)
    VALUES (
        p_order->>'customerId',
        COALESCE(p_order->>'status', 'PENDING'),
        COALESCE((p_order->>'createdAt')::timestamp, NOW())
    )
    RETURNING id INTO new_order_id;

    IF jsonb_typeof(p_order->'lines') = 'array' AND jsonb_array_length(p_order->'lines') > 0 THEN
        FOR line IN SELECT * FROM jsonb_array_elements(p_order->'lines')
        LOOP
            INSERT INTO order_lines (order_id, product_id, quantity, unit_price)
            VALUES (
                new_order_id,
                line->>'productId',
                (line->>'quantity')::int,
                (line->>'unitPrice')::numeric
            );
        END LOOP;
    END IF;
END;
$$;

-- OrderRepository.updateStatus(Long id, OrderStatus status) -> void
CREATE OR REPLACE FUNCTION order_repository_update_status_v1(p_id BIGINT, p_status TEXT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE orders SET status = p_status WHERE id = p_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Order not found: %', p_id
            USING ERRCODE = 'P0002';
    END IF;
END;
$$;

-- OrderRepository.findBy(OrderSpec spec) -> List<Order>
--
-- The Specification tree travels as a single JSONB argument. Its leaf VALUES are never
-- concatenated into SQL: the helper below walks the tree into a WHERE clause that references
-- each leaf value by its JSON *path* into the bound argument ($1 #>> path), and the main
-- function runs that clause with EXECUTE ... USING spec — so values are bound, not injected.
CREATE OR REPLACE FUNCTION order_repository_find_by_v1_spec_to_sql(node JSONB, path TEXT[])
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    kind TEXT := node->>'kind';
    parts TEXT[] := ARRAY[]::TEXT[];
    i INT;
BEGIN
    CASE kind
        WHEN 'and' THEN
            FOR i IN 0 .. COALESCE(jsonb_array_length(node->'specs'), 0) - 1 LOOP
                parts := parts || order_repository_find_by_v1_spec_to_sql(
                    node->'specs'->i, path || ARRAY['specs', i::text]);
            END LOOP;
            RETURN CASE WHEN cardinality(parts) = 0 THEN 'TRUE'
                        ELSE '(' || array_to_string(parts, ' AND ') || ')' END;
        WHEN 'or' THEN
            FOR i IN 0 .. COALESCE(jsonb_array_length(node->'specs'), 0) - 1 LOOP
                parts := parts || order_repository_find_by_v1_spec_to_sql(
                    node->'specs'->i, path || ARRAY['specs', i::text]);
            END LOOP;
            RETURN CASE WHEN cardinality(parts) = 0 THEN 'FALSE'
                        ELSE '(' || array_to_string(parts, ' OR ') || ')' END;
        WHEN 'not' THEN
            RETURN '(NOT ' || order_repository_find_by_v1_spec_to_sql(
                node->'spec', path || ARRAY['spec']) || ')';
        WHEN 'forCustomer' THEN
            RETURN format('o.customer_id = ($1 #>> %L::text[])', path || ARRAY['customerId']);
        WHEN 'hasStatus' THEN
            RETURN format('o.status = ($1 #>> %L::text[])', path || ARRAY['status']);
        WHEN 'createdAfter' THEN
            RETURN format('o.created_at > ($1 #>> %L::text[])::timestamp', path || ARRAY['t']);
        WHEN 'highValue' THEN
            RETURN format('(SELECT COALESCE(SUM(ol.quantity * ol.unit_price), 0) FROM order_lines ol'
                          || ' WHERE ol.order_id = o.id) >= ($1 #>> %L::text[])::numeric',
                          path || ARRAY['min']);
        ELSE
            RAISE EXCEPTION 'Unknown OrderSpec kind: %', kind;
    END CASE;
END;
$$;

CREATE OR REPLACE FUNCTION order_repository_find_by_v1(spec JSONB)
RETURNS SETOF JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    where_clause TEXT := order_repository_find_by_v1_spec_to_sql(spec, ARRAY[]::TEXT[]);
    ids BIGINT[];
BEGIN
    -- Resolve matching order ids with the dynamic, parameter-bound predicate ...
    EXECUTE 'SELECT array_agg(o.id ORDER BY o.created_at DESC, o.id DESC) FROM orders o WHERE ' || where_clause
        INTO ids USING spec;

    -- ... then build the aggregate JSON statically (no dynamic SQL in the projection).
    RETURN QUERY
    SELECT jsonb_build_object(
        'id', o.id,
        'customerId', o.customer_id,
        'status', o.status,
        'createdAt', o.created_at,
        'lines', COALESCE((
            SELECT jsonb_agg(jsonb_build_object(
                'productId', ol.product_id,
                'quantity', ol.quantity,
                'unitPrice', ol.unit_price
            ) ORDER BY ol.id)
            FROM order_lines ol WHERE ol.order_id = o.id
        ), '[]'::jsonb)
    )
    FROM orders o
    WHERE o.id = ANY(ids)
    ORDER BY array_position(ids, o.id);
END;
$$;
