package net.unit8.tieto.generator.output;

import net.unit8.tieto.generator.ai.GeneratedFunction;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/** Parsing edge cases for the delimited-block file model. */
class SqlFunctionFileTest {

    @Test
    void parseToleratesCrlfLineEndings() {
        // A file written with LF and later checked out with CRLF must still be recognised as
        // delimited (not misclassified as legacy, which would append-duplicate on regeneration).
        String content = ("-- Generated by tieto-generator\n\n"
                + "-- tieto:begin order_repository_a_v1\n"
                + "CREATE OR REPLACE FUNCTION order_repository_a_v1() RETURNS int LANGUAGE sql AS $$ SELECT 1 $$;\n"
                + "-- tieto:end order_repository_a_v1\n").replace("\n", "\r\n");

        SqlFunctionFile file = SqlFunctionFile.parse(content);

        assertThat(file.isLegacy()).as("CRLF markers are recognised").isFalse();
        file.putAll(List.of(fn("order_repository_a_v1")));
        // Re-rendered once (merged/replaced), not accumulated.
        assertThat(file.render().split("-- tieto:begin order_repository_a_v1", -1)).hasSize(2);
    }

    @Test
    void parseTreatsRawSqlBeforeTheFirstMarkerAsLegacy() {
        // Raw SQL above the first marker cannot be merged safely (it would be swallowed into the
        // header and duplicated), so the file is treated as legacy for the append fallback.
        String content = "-- header comment\n"
                + "CREATE OR REPLACE FUNCTION order_repository_raw_v1() RETURNS int LANGUAGE sql AS $$ SELECT 1 $$;\n\n"
                + "-- tieto:begin order_repository_a_v1\n"
                + "CREATE OR REPLACE FUNCTION order_repository_a_v1() RETURNS int LANGUAGE sql AS $$ SELECT 1 $$;\n"
                + "-- tieto:end order_repository_a_v1\n";

        assertThat(SqlFunctionFile.parse(content).isLegacy()).isTrue();
    }

    @Test
    void aCleanFileWithOnlyHeaderCommentsAndMarkersIsNotLegacy() {
        String content = "-- Generated by tieto-generator\n-- Source: OrderRepository\n\n"
                + "-- tieto:begin order_repository_a_v1\n"
                + "CREATE OR REPLACE FUNCTION order_repository_a_v1() RETURNS int LANGUAGE sql AS $$ SELECT 1 $$;\n"
                + "-- tieto:end order_repository_a_v1\n";

        assertThat(SqlFunctionFile.parse(content).isLegacy()).isFalse();
    }

    @Test
    void parseEndsABlockOnItsOwnNameNotAnUnrelatedEndMarkerInTheBody() {
        // A body line that looks like a DIFFERENT block's end marker must not truncate this block.
        String content = "-- tieto:begin order_repository_a_v1\n"
                + "CREATE OR REPLACE FUNCTION order_repository_a_v1() RETURNS int LANGUAGE plpgsql AS $$\n"
                + "-- tieto:end order_repository_other_v1\n"
                + "BEGIN RETURN 7; END\n"
                + "$$;\n"
                + "-- tieto:end order_repository_a_v1\n";

        SqlFunctionFile file = SqlFunctionFile.parse(content);

        assertThat(file.isLegacy()).isFalse();
        // The whole body survived — the unrelated end marker did not truncate it.
        assertThat(file.render()).contains("RETURN 7").contains("$$");
    }

    private static GeneratedFunction fn(String name) {
        return new GeneratedFunction(name,
                "CREATE OR REPLACE FUNCTION " + name + "() RETURNS int LANGUAGE sql AS $$ SELECT 2 $$", null);
    }
}
