package net.unit8.tieto.generator.output;

import net.unit8.tieto.generator.ai.GeneratedFunction;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class SqlFileWriterTest {

    private static GeneratedFunction fn(String name) {
        return new GeneratedFunction(name,
                "CREATE OR REPLACE FUNCTION " + name + "() RETURNS int LANGUAGE sql AS $$ SELECT 1 $$", null);
    }

    private static String read(Path dir) throws IOException {
        return Files.readString(dir.resolve("order_repository.sql"));
    }

    @Test
    void appendPreservesFunctionsAlreadyInTheFile(@TempDir Path dir) throws IOException {
        SqlFileWriter writer = new SqlFileWriter();
        writer.write(dir, "OrderRepository", List.of(fn("order_repository_a_v1")), true, "TestProvider model=test");

        // A later non-force run generated only the new function (the old one was skipped).
        writer.write(dir, "OrderRepository", List.of(fn("order_repository_b_v1")), false, "TestProvider model=test");

        String content = read(dir);
        assertThat(content)
                .contains("FUNCTION order_repository_a_v1()")   // preserved
                .contains("FUNCTION order_repository_b_v1()");  // added
    }

    @Test
    void replaceRewritesTheWholeFile(@TempDir Path dir) throws IOException {
        SqlFileWriter writer = new SqlFileWriter();
        writer.write(dir, "OrderRepository", List.of(fn("order_repository_a_v1")), true, "TestProvider model=test");

        // A --force run regenerates everything and rewrites the file.
        writer.write(dir, "OrderRepository", List.of(fn("order_repository_b_v1")), true, "TestProvider model=test");

        String content = read(dir);
        assertThat(content)
                .doesNotContain("order_repository_a_v1")
                .contains("FUNCTION order_repository_b_v1()");
    }

    @Test
    void writesAHeaderAndAFreshFile(@TempDir Path dir) throws IOException {
        new SqlFileWriter().write(dir, "OrderRepository", List.of(fn("order_repository_a_v1")), false, "TestProvider model=test");

        assertThat(read(dir))
                .startsWith("-- Generated by tieto-generator")
                .contains("-- Generator: TestProvider model=test")
                .contains("FUNCTION order_repository_a_v1()");
    }
}
